name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1 # TODO: update to "release" once 0.15.2 isn't broken
      - run: zig fmt --ast-check --check .
      - run: zig build
      - run: zig build -Dlsp=false -Ddebugger=false
      - run: zig build test
      - run: zig build test -Doptimize=ReleaseFast
      - run: zig build -Dtarget=x86_64-windows-gnu
      - run: zig build -Dtarget=x86_64-linux-musl
      - run: zig build -Dtarget=aarch64-macos
      - run: zig build -Dtarget=wasm32-wasi
